import os, re

translations = {
"Select products to begin": "اختر المنتجات للبدء",
"MUNEEFA TRADING": "مؤسسة منيفة للتجارة",
"Manage your shop details, brand identity, branches, and secure staff accounts.": "إدارة تفاصيل متجرك، هوية علامتك التجارية، الفروع، وتأمين حسابات الموظفين.",
"This customer has credit invoices that are approaching or have exceeded the 30-day limit.": "يوجد لدى هذا العميل فواتير ائتمان تقترب من أو تجاوزت حد 30 يوماً.",
"Paid (QAR)": "المدفوع (ر.ق)",
"Search by name or scan barcode...": "ابحث بالاسم أو امسح الباركود...",
"CHANGE": "الباقي",
"Branch Name": "اسم الفرع",
"System Ready": "النظام جاهز",
"Total Inventory Details": "إجمالي تفاصيل المخزون",
"(Leave blank to keep current)": "(اتركه فارغاً للاحتفاظ بالحالي)",
"Transfer Details": "تفاصيل التحويل",
"Edit Branch": "تعديل الفرع",
"Customer": "العميل",
"Thanks For Coming To Our Store": "شكرا لزيارتكم متجرنا",
"Detailed breakdown of records": "تفصيل السجلات",
"Total Revenue": "إجمالي الإيرادات",
"No products recorded yet. Click \\\"Add Product\\\" to start tracking.": "لم يتم تسجيل أي منتجات بعد. انقر على \"إضافة منتج\" لبدء التتبع.",
"Execute Transfer": "تنفيذ التحويل",
"No barcode generated yet.": "لم يتم إنشاء باركود بعد.",
"Initial Stock Count": "الجرد المبدئي للمخزون",
"Start Cash": "الدرج في البداية",
"TOTAL EXPENSES (THIS MONTH)": "إجمالي المصروفات (هذا الشهر)",
"QAR 0.00": "ر.ق 0.00",
"Cashier Performance": "أداء الكاشير",
"To Branch (Destination)": "إلى الفرع (الوجهة)",
"Configure administrative and cashier accounts for the system.": "قم بتهيئة الحسابات الإدارية وحسابات الكاشير للنظام.",
"QAR": "ر.ق",
"Loyalty Points": "نقاط الولاء",
"Quantity Transferred": "الكمية المحولة",
"Cost of Products Sold": "تكلفة المنتجات المباعة",
"Outstanding Balance": "الرصيد المتبقي",
"Delete Expense": "حذف المصروف",
"Change Due:": "الباقي المستحق:",
"Shift Logs": "سجلات الورديات",
"Select a branch from the top menu first": "حدد فرعا من القائمة العلوية أولاً",
"Confirmation Required": "مطلوب التأكيد",
"Expiry Date (Optional)": "تاريخ الانتهاء (اختياري)",
"End Time": "وقت النهاية",
"Net Profit": "صافي الربح",
"Enable to add items as Returns (negative qty)": "تفعيل لإضافة الأصناف كمرتجع (كمية سالبة)",
"CASH": "نقداً",
"Your POS terminal and database are perfectly synchronized.": "جهاز نقاط البيع وقاعدة البيانات الخاصة بك متزامنة تماما.",
"THANK YOU": "شكرا لكم",
"Confirm Receipt": "تأكيد الاستلام",
"Supplier Profile & History": "ملف المورد والسجل",
"Product Sales Revenue": "إيرادات مبيعات المنتجات",
"View Branch Details": "عرض تفاصيل الفرع",
"No shifts found in this period.": "لا توجد ورديات في هذه الفترة.",
"No sales in this period.": "لا توجد مبيعات في هذه الفترة.",
"Cost Price (QAR)": "سعر التكلفة (ر.ق)",
"Stock Count": "كمية المخزون",
"Edit Expense": "تعديل المصروف",
"Created By": "أنشئ بواسطة",
"You are currently viewing all GRNs globally. To create a new GRN, please select a specific branch from the dropdown menu in the top right corner.": "أنت تعرض حالياً جميع مذكرات استلام البضائع عالمياً. لإنشاء مذكرة جديدة، يرجى تحديد فرع من القائمة في الزاوية العلوية اليمنى.",
"Product Name": "اسم المنتج",
"Slim 4 with Twig & SQLite": "سليم 4 مع تويج و اس كيو لايت",
"Current Stock": "المخزون الحالي",
"Branch Code": "رمز الفرع",
"Close": "إغلاق",
"Contact Phone": "رقم التواصل",
"Received Items": "الأصناف المستلمة",
"Supplier": "المورد",
"Branch Required": "الفرع مطلوب",
"Contact : 7096 4494": "رقم التواصل: 7096 4494",
"Inventory & Stock": "الجرد والمخزون",
"to": "إلى",
"Direct Repair Costs": "تكاليف الإصلاح المباشرة",
"Outstanding Dues": "المستحقات غير المسددة",
"Customer Profile & History": "ملف العميل وسجل المعاملات",
"Update Pricing": "تحديث الأسعار",
"Stock Units": "وحدات المخزون",
"Purchase History": "تاريخ الشراء",
"Street address": "عنوان الشارع",
"Cheque": "شيك",
"Fawran:": "فوران:",
"Cost of Goods Sold (COGS)": "تكلفة البضائع المباعة",
"Total Sold": "إجمالي المباع",
"Contact number": "رقم التواصل",
"No categories found.": "لم يتم العثور على فئات.",
"Bank Transfer": "تحويل بنكي",
"Cash:": "نقداً:",
"Total (QAR)": "الإجمالي (ر.ق)",
"Branch Management": "إدارة الفروع",
"Create Branch": "إنشاء فرع",
"Stock Manager (Inventory Only)": "مدير المخزون (فقط للمخزون)",
"Repair Services Revenue": "إيرادات خدمات الإصلاح",
"Admin (All Branches)": "مسؤول (جميع الفروع)",
"Actual Ending": "النهاية الفعلية",
"Select Supplier": "اختر المورد",
"Quick Actions": "إجراءات سريعة",
"Total Period Expenses": "إجمالي مصروفات الفترة",
"There are no stock transfers recorded yet.": "لا توجد تحويلات مخزون مسجلة بعد.",
"All Stock Levels Optimal": "مستويات المخزون مثالية",
"Min Stock Alert": "تنبيه انخفاض المخزون",
"Immediate Action Needed": "يتطلب إجراء فوري",
"New Transfer": "تحويل جديد",
"Total Inventory Items": "إجمالي أصناف المخزون",
"Search expenses by category or note...": "بحث عن المصروفات بالفئة أو الملاحظة...",
"New Unit Name (e.g. PCS)...": "اسم الوحدة الجديدة (مثل قطعة)...",
"Period Expenses Details": "تفاصيل مصروفات الفترة",
"Cashier (POS & Basic Inventory)": "كاشير (نقطة البيع والمخزون الأساسي)",
"From Branch (Source)": "من الفرع (المصدر)",
"Open": "مفتوح",
"No items selected": "لم يتم اختيار عناصر",
"General Expenses": "مصروفات عامة",
"Select Category": "اختر الفئة",
"No items are currently running low.": "لا توجد عناصر تنفد حاليا.",
"Leave empty to auto-generate": "اتركه فارغا للإنشاء التلقائي",
"Select products to add to GRN": "حدد المنتجات لإضافتها إلى المذكرة",
"No payments recorded yet.": "لا توجد مدفوعات مسجلة بعد.",
"Receipt Details": "تفاصيل الإيصال",
"MT POS and ERP": "برنامج MT لنقاط البيع وإدارة الموارد",
"Expected": "المتوقع",
"Overdue Credit Alerts (>= 27 Days)": "تنبيهات الائتمان المتأخر (أكثر من 27 يوما)",
"Low Stock Alerts": "تنبيهات المخزون المنخفض",
"TENDERED": "المدفوع",
"Shop No 02, Umm Al Dome Street.": "محل رقم 2، شارع أم الدوم.",
"Unassigned": "غير معين",
"Inventory is fully stocked!": "المخزون ممتلئ!",
"Fractional": "قابلة للكسر (جزئي)",
"Operating Expenses": "مصروفات التشغيل",
"https://example.com/logo.png": "https://example.com/logo.png",
"Assign to Branch": "تعيين إلى فرع",
"Manage purchase receipts and supplier deliveries.": "إدارة إيصالات الشراء وتسليمات الموردين.",
"Due (Credit)": "المستحق (ائتمان)",
"Login | MT POS and ERP": "تسجيل الدخول | برنامج MT",
"Card:": "بطاقة:",
"Code": "الرمز",
"Purchases / GRN": "المشتريات / مذكرات الاستلام",
"Method": "طريقة الدفع",
"e.g. Branch C": "مثال: الفرع ج",
"Shop Address": "عنوان المحل",
"Transactions": "العمليات",
"Total Stock Value": "إجمالي قيمة المخزون",
"100 points = QAR 1.00 discount": "100 نقطة = خصم 1.00 ر.ق",
"Days Elapsed": "الأيام المنقضية",
"Note: Selling item should be returned within 24hrs for exchange.": "ملاحظة: يجب إرجاع السلع المباعة خلال 24 ساعة للاستبدال.",
"Save Expense": "حفظ المصروف",
"Move inventory instantly": "نقل المخزون فوراً",
"ID": "رقم التعريف",
"No GRNs found for this supplier.": "لا توجد مذكرات استلام لهذا المورد.",
"Create Account": "إنشاء حساب",
"Period Sales": "مبيعات الفترة",
"Profit & Loss Statement": "بيان الأرباح والخسائر",
"e.g. BR-C": "مثال: BR-C",
"Product": "المنتج",
"New Password": "كلمة المرور الجديدة",
"Action Required: Overdue Credit": "مطلوب اتخاذ إجراء: ائتمان متأخر",
"- QAR 0.00": "- ر.ق 0.00",
"Shifts Report": "تقرير الورديات",
"Revenue": "الإيرادات",
"Select Destination": "اختر الوجهة",
"No units found.": "لم يتم العثور على وحدات.",
"No Transfers Found": "لا توجد تحويلات",
"For period:": "عن الفترة:",
"Search payments...": "البحث في المدفوعات...",
"Allow Decimal/Fractional Quantities (e.g., 1.5 KG)": "السماح بالكميات الكسرية (مثال 1.5 كيلو)",
"Period Transactions": "عمليات الفترة",
"SECURE": "آمن",
"ONLINE": "متصل",
"Confirm Addition": "تأكيد الإضافة",
"Profit & Loss": "الأرباح والخسائر",
"Operations": "العمليات",
"No expenses recorded yet. Click \\\"Add Expense\\\" to start tracking.": "لم يتم تسجيل أي مصروفات. انقر فوق \"إضافة مصروف\" للبدء.",
"Units to Add": "الوحدات للإضافة",
"Total Expenses": "إجمالي المصروفات",
"Database": "قاعدة البيانات",
"Cost of Goods & Deductions": "تكلفة البضائع والخصومات",
"Cash Sales": "المبيعات النقدية",
"Access Role": "صلاحية الوصول",
"Add New Product": "إضافة منتج جديد",
"Branch": "الفرع",
"Transferred Items": "الأصناف المحولة",
"e.g. Paid electricity bill for January": "مثال: دفع فاتورة الكهرباء لشهر يناير",
"Save Customer": "حفظ العميل",
"Crunching the numbers...": "جاري حساب الأرقام...",
"Total Period Revenue": "إجمالي إيرادات الفترة",
"GRN Details": "تفاصيل مذكرة الاستلام",
"Select a category...": "اختر فئة...",
"No sales records found matching your search.": "لم يتم العثور على مبيعات تطابق بحثك.",
"There are no Goods Received Notes recorded yet.": "لا توجد مذكرات استلام بضائع مسجلة بعد.",
"Exchange Items from this Sale": "استبدال عناصر من هذه البيعة",
"Remove item": "إزالة العنصر",
"- QAR 0": "- ر.ق 0",
"Low Stock Alert (Bottom 10)": "تنبيه المخزون المنخفض (أقل 10)",
"Staff Accounts": "حسابات الموظفين",
"Amount Owed": "المبلغ المستحق",
"Slim Framework App": "تطبيق إطار عمل سليم",
"Invoice": "الفاتورة",
"Storage sync": "مزامنة التخزين",
"Branch Performance": "أداء الفرع",
"Generate": "إنشاء",
"Add Stock": "إضافة مخزون",
"Sales Report": "تقرير المبيعات",
"No items added": "لم يتم إضافة أصناف",
"Shop Name": "اسم المحل",
"Total Stock Items": "إجمالي أصناف المخزون",
"Remaining: QAR 0.00": "المتبقي: ر.ق 0.00",
"No purchases found for this customer.": "لم يتم العثور على مشتريات لهذا العميل.",
"Revenue by Payment Method": "الإيرادات حسب طريقة الدفع",
"Delivery reference, etc.": "مرجع التوصيل، إلخ.",
"Contact Info": "معلومات التواصل",
"Products Revenue": "إيرادات المنتجات",
"Print": "طباعة",
"Period Revenue Details": "تفاصيل إيرادات الفترة",
"Shop Logo URL (Optional)": "رابط شعار المحل (اختياري)",
"This will be added to the current stock count.": "سيتم إضافة هذا إلى رصيد المخزون الحالي.",
"Owner (All Branches)": "المالك (جميع الفروع)",
"Add New Expense": "إضافة مصروف جديد",
"Save Product": "حفظ المنتج",
"Select products to transfer": "اختر المنتجات للتحويل",
"Item Name": "اسم الصنف",
"Split Amounts": "تقسيم المبالغ",
"OWNER": "المالك",
"Search GRNs...": "البحث في مذكرات الاستلام...",
"New Category Name...": "اسم فئة جديدة...",
"Invoice & Date": "الفاتورة والتاريخ",
"Sale Date": "تاريخ البيع",
"Start Time": "وقت البدء",
"Select Source": "اختر المصدر",
"Closed": "مغلق",
"Total Retail Value": "إجمالي قيمة البيع",
"Reason for transfer, vehicle no, etc.": "سبب التحويل، رقم المركبة، إلخ.",
"Search purchases...": "البحث في المشتريات...",
"Al Muaither": "المعيذر",
"Save Supplier": "حفظ المورد",
"Total Inventory Cost": "إجمالي تكلفة المخزون",
"Reference:": "المرجع:",
"Tendered Amount (Cash)": "المبلغ المدفوع (نقداً)",
"Barcode (Optional)": "الباركود (اختياري)",
"Notes": "ملاحظات",
"Total COGS": "إجمالي تكلفة البضائع",
"Add New Branch": "إضافة فرع جديد",
"Final Net Profit": "الصافي النهائي للربح"
}

with open('public/lang.php', 'r', encoding='utf-8') as f:
    content = f.read()

for k, v in translations.items():
    safe_k = k.replace("'", "\\'")
    safe_v = v.replace("'", "\\'")
    pattern = f"'{re.escape(safe_k)}'\\s*=>\\s*'{re.escape(safe_k)}'"
    replacement = f"'{safe_k}' => '{safe_v}'"
    content = re.sub(pattern, replacement, content)

with open('public/lang.php', 'w', encoding='utf-8') as f:
    f.write(content)
